// Generated by scripts/build-product-docs.mjs. Do not edit manually.
import type { ProductDoc } from './types'

export const productDocs: ProductDoc[] = [
  {
    "id": "product",
    "route": "/product",
    "title": "Product",
    "status": "stable",
    "summary": "LOCAL AI OS makes one private Linux/Codex workflow observable and bounded: relevant context, approved write scope, verification, and a report for the owner.",
    "blocks": [
      {
        "heading": "Public repository and delivery",
        "body": "The public repository contains this product site, the proof contract, reviewed technical documentation, release checks, and a GitHub Pages build. It is not a downloadable copy of a customer's runtime or credentials.",
        "bullets": [
          "Public: product documentation, schemas, safe proof data, and site build logic.",
          "Delivered during implementation: reviewed workstation configuration, scoped policies, integration choices, and acceptance artifacts.",
          "Local-only: customer source, secrets, prompts, raw responses, runtime state, and private reports."
        ]
      },
      {
        "heading": "Capability status",
        "body": "Stable means a documented, bounded practice exists. Experimental means it needs owner review per installation. Planned means it is not delivered by cloning this repository. Unavailable means no claim is made.",
        "bullets": [
          "No universal autonomy promise.",
          "No unrestricted shell bridge.",
          "No claim that a public-site clone installs LOCAL AI OS."
        ]
      }
    ]
  },
  {
    "id": "architecture",
    "route": "/architecture",
    "title": "Architecture",
    "status": "stable",
    "summary": "The architecture keeps ownership explicit rather than creating another control plane.",
    "blocks": [
      {
        "heading": "Data and ownership flow",
        "body": "Obsidian holds human-readable decisions and operating memory. Git holds versioned source and public projections. Context packs are generated task inputs. Run reports are generated evidence. Atlas is a read-only view, never a replacement source of truth.",
        "bullets": [
          "Source of truth: reviewed notes and tracked source.",
          "Generated consumers: context packs, reports, telemetry, release status, and Atlas snapshots.",
          "Public projection: this site and approved proof artifacts only."
        ]
      },
      {
        "heading": "Execution flow",
        "body": "Request → scoped context → allowed work item → bounded write → allowlisted verification → normalized report → owner handoff. Each arrow has a boundary; none is a claim of unattended general autonomy.",
        "bullets": [
          "The worker does not decide its own trust boundary.",
          "A failed check remains evidence, not hidden success."
        ]
      }
    ]
  },
  {
    "id": "runtime",
    "route": "/runtime",
    "title": "Runtime",
    "status": "experimental",
    "summary": "Runtime is a role map, not a single product dependency: local models, a human UI, guarded assistant paths, and deterministic checks can be assembled around the existing workstation.",
    "blocks": [
      {
        "heading": "Roles and health",
        "body": "Ollama provides local model execution where selected. Open WebUI is a human-facing local UI and knowledge surface. OpenClaw and OpenHarness are guarded task/check surfaces where adopted. Their health is assessed separately from the static product-site build.",
        "bullets": [
          "Model routing is configuration and installation-specific.",
          "Fallback is an explicit operator decision, not a silent cloud escalation.",
          "A missing service is reported as unavailable, not simulated in the portal."
        ]
      },
      {
        "heading": "Status",
        "body": "The runtime integration is experimental because exact components, ports, and resource limits are approved during implementation. The safety and reporting boundaries are stable.",
        "bullets": []
      }
    ]
  },
  {
    "id": "context-memory",
    "route": "/context-memory",
    "title": "Context and memory",
    "status": "stable",
    "summary": "The purpose of context engineering is to stop an agent from replaying an entire workstation or conversation when one task needs a bounded brief.",
    "blocks": [
      {
        "heading": "Context packs",
        "body": "A context pack selects reviewed notes, repository facts, task scope, freshness metadata, and verification commands. It records provenance and token budget so an owner can understand why a source was included.",
        "bullets": [
          "Canonical notes outrank generated summaries.",
          "Raw conversation mirrors, secrets, and generated clutter are excluded from normal packs.",
          "A stale or denied source is visible in the report."
        ]
      },
      {
        "heading": "Freshness and provenance",
        "body": "RAG is a retrieval layer, not a second memory. Each installation defines eligible sources, freshness expectations, redaction rules, and budget limits before enabling a workflow.",
        "bullets": []
      }
    ]
  },
  {
    "id": "codex-orchestrator",
    "route": "/codex-orchestrator",
    "title": "Codex Orchestrator",
    "status": "stable",
    "summary": "Codex is treated as a controlled executor. It receives a work item, a context pack, writable boundaries, required checks, and a required report shape.",
    "blocks": [
      {
        "heading": "Scope and lifecycle",
        "body": "A work item names the allowed repository/branch, file scope, constraints, verification commands, and rollback expectation. The lifecycle can move through preparation, review, execution, verified, failed, or blocked states.",
        "bullets": [
          "Write access is scoped; arbitrary command wandering is not a product feature.",
          "Verification commands are allowlisted and their outcomes are kept in the run report.",
          "Queue ownership stays with the orchestrator; Atlas does not become a second worker."
        ]
      },
      {
        "heading": "Run report",
        "body": "The handoff summarizes changed-file categories, checks, blockers, decision, and next exact action. It does not expose raw prompts, responses, or customer source.",
        "bullets": []
      }
    ]
  },
  {
    "id": "project-atlas",
    "route": "/project-atlas",
    "title": "Project Atlas",
    "status": "experimental",
    "summary": "Project Atlas is an operator lens over sanitized, generated state: queues, current reports, status, freshness, and next actions.",
    "blocks": [
      {
        "heading": "Read-only visibility",
        "body": "Atlas can show a report and guide an operator to a governed enqueue route, but it does not own the task queue, canonical decisions, or arbitrary command execution.",
        "bullets": [
          "Shows evidence and state, not hidden control.",
          "Reads normalized status rather than raw credentials or conversation logs.",
          "Health is time-sensitive and must be refreshed at operation time."
        ]
      },
      {
        "heading": "Status",
        "body": "The visibility model is stable. Individual Atlas widgets and integration endpoints remain experimental installation details.",
        "bullets": []
      }
    ]
  },
  {
    "id": "integrations",
    "route": "/integrations",
    "title": "Integrations",
    "status": "planned",
    "summary": "Integrations are selected to extend the existing local-first contour, not to introduce a parallel always-on agent stack.",
    "blocks": [
      {
        "heading": "Installation choices",
        "body": "An implementation can connect approved local model services, repositories, notes, and operator surfaces. Each connector receives a named owner, data classification, least-privilege boundary, and rollback route.",
        "bullets": [
          "No integration receives unrestricted access by default.",
          "Customer-specific connectors are not published in this repository.",
          "Unapproved cloud transfer is unavailable by design."
        ]
      },
      {
        "heading": "Status",
        "body": "Integration catalogues are planned. The review process and public/private boundary are stable.",
        "bullets": []
      }
    ]
  },
  {
    "id": "security",
    "route": "/security",
    "title": "Security",
    "status": "stable",
    "summary": "Security begins with data classification and least privilege, not a claim that all agent work is safe by default.",
    "blocks": [
      {
        "heading": "Public and private boundary",
        "body": "Public artifacts may contain reviewed architecture, aggregate proof measurements, changed-file categories, verification summaries, and release metadata. They never contain private paths, raw prompts or responses, credentials, logs, PII, customer code, or unapproved repository names.",
        "bullets": [
          "Secrets stay in local secret stores or owner-approved deployment mechanisms.",
          "Redaction happens before public proof generation.",
          "Permissions define readable sources, writable roots, commands, and operators."
        ]
      },
      {
        "heading": "Audit and failure",
        "body": "Run reports and verification evidence provide an audit-friendly summary. They do not replace host security monitoring. Any uncertain publication is withheld.",
        "bullets": []
      }
    ]
  },
  {
    "id": "deployment",
    "route": "/deployment",
    "title": "Deployment",
    "status": "planned",
    "summary": "Implementation is a reviewed topology, not an installer promise hidden inside a marketing page.",
    "blocks": [
      {
        "heading": "Topology and requirements",
        "body": "The delivery maps selected services, local ports, storage ownership, system requirements, startup order, and health checks for one agreed workstation. The public site is independently deployed as a static GitHub Pages artifact.",
        "bullets": [
          "The public repository builds the site and its reviewed docs.",
          "Runtime installation depends on owner-approved components and existing workstation state.",
          "Updates and rollback use versioned source, backups, and documented checks."
        ]
      },
      {
        "heading": "Status",
        "body": "Static site deployment is stable. A universal runtime installer is planned and is not available from this repository.",
        "bullets": []
      }
    ]
  },
  {
    "id": "acceptance",
    "route": "/acceptance",
    "title": "Acceptance",
    "status": "stable",
    "summary": "Acceptance is the owner-facing proof that the agreed workflow and boundaries were actually checked.",
    "blocks": [
      {
        "heading": "Handoff evidence",
        "body": "An acceptance report lists declared artifacts, scope, completed checks, known limitations, recovery route, and next action. A failed or unavailable measurement stays visible.",
        "bullets": [
          "Verification evidence is mandatory for a successful run.",
          "Acceptance compares delivery with the agreed scope, not with an autonomy claim.",
          "The owner retains the report and operating decisions."
        ]
      },
      {
        "heading": "Status",
        "body": "The report shape and verification requirement are stable. Customer-specific acceptance criteria are agreed before an implementation starts.",
        "bullets": []
      }
    ]
  },
  {
    "id": "operations",
    "route": "/operations",
    "title": "Operations",
    "status": "experimental",
    "summary": "Operations make current state inspectable without turning runtime exports into a second source of truth.",
    "blocks": [
      {
        "heading": "Health and routine work",
        "body": "Operators use bounded health checks, queue state, freshness, release status, and recent normalized reports. A degraded signal is investigated from its incident evidence instead of being presented as healthy.",
        "bullets": [
          "Routine maintenance uses documented checks and known owners.",
          "Runtime state remains local and sanitized before any aggregate visibility.",
          "Model routing and service state are refreshed when the task requires them."
        ]
      },
      {
        "heading": "Status",
        "body": "The operational model is experimental at product level because the exact services are implementation-specific.",
        "bullets": []
      }
    ]
  },
  {
    "id": "recovery",
    "route": "/recovery",
    "title": "Recovery",
    "status": "stable",
    "summary": "Recovery is a source-driven route: preserve data, know ownership, test restore, and keep rollback separate from a live incident workaround.",
    "blocks": [
      {
        "heading": "Backup and rollback",
        "body": "Each implementation documents what is backed up, who can restore it, the order of recovery, and a restore dry-run. A bad product-site release is rolled back by reverting or fixing the versioned source and redeploying.",
        "bullets": [
          "Backups do not imply publication of their contents.",
          "Recovery instructions do not include secrets in public documentation.",
          "GUI workarounds that force software rendering are incident diagnostics, not accepted final states."
        ]
      }
    ]
  },
  {
    "id": "releases",
    "route": "/releases",
    "title": "Releases",
    "status": "stable",
    "summary": "The release train ties source change, QA, generated public data, Pages build, and post-release memory together.",
    "blocks": [
      {
        "heading": "Release gates",
        "body": "The public site generates release status, validates documentation and proof data, lints TypeScript, builds production assets, validates direct routes, and runs a high-severity dependency audit.",
        "bullets": [
          "Generated documentation must match its reviewed Markdown source.",
          "Proof pages must pass schema, forbidden-content, and verification-evidence checks.",
          "A release note records known limits rather than inventing success metrics."
        ]
      }
    ]
  },
  {
    "id": "roadmap",
    "route": "/roadmap",
    "title": "Roadmap",
    "status": "planned",
    "summary": "The roadmap is intentionally bounded by evidence rather than a promise of a universal AI operating system.",
    "blocks": [
      {
        "heading": "Next evidence",
        "body": "The next commercial milestone is an owner-approved external workflow with baseline criteria agreed before work, a sanitized proof artifact, and explicit permission to share it.",
        "bullets": [
          "More founder proofs only when their evidence is public-safe.",
          "Deployment automation only after its topology and rollback contract are proven.",
          "Broader integrations only when they preserve the existing control boundaries."
        ]
      }
    ]
  },
  {
    "id": "docs",
    "route": "/docs",
    "title": "Documentation",
    "status": "stable",
    "summary": "This portal is a generated public snapshot for technical due diligence. It is deliberately not a dump of a private Obsidian vault or runtime directory.",
    "blocks": [
      {
        "heading": "Source and drift",
        "body": "Reviewed Markdown in this directory is converted into typed site data. QA checks the manifest, generated output, routes, public-content boundary, and proof data.",
        "bullets": [
          "Obsidian remains the human-readable source of truth for the installed system.",
          "Public docs are a curated projection with stable URLs.",
          "Generated output is checked for drift before release."
        ]
      }
    ]
  },
  {
    "id": "faq",
    "route": "/faq",
    "title": "FAQ",
    "status": "stable",
    "summary": "LOCAL AI OS is a scoped implementation and operating contour for one private Linux workflow, not a general-purpose autonomous agent product.",
    "blocks": [
      {
        "heading": "What can I evaluate publicly?",
        "body": "You can inspect the product site, proof contract, founder proofs, technical portal, release checks, static deployment configuration, and public documentation. Customer configurations, runtime state, source, prompts, and secrets are not public.",
        "bullets": []
      },
      {
        "heading": "Does cloning the repository install the system?",
        "body": "No. It builds the public product surface. Runtime and customer configuration are selected, reviewed, installed, and accepted in the delivery scope.",
        "bullets": []
      },
      {
        "heading": "Are metrics guaranteed?",
        "body": "No. A proof shows only recorded measurements. Missing measurements are explicitly unavailable. No customer result is implied by a founder proof.",
        "bullets": []
      }
    ]
  }
]
